CALL englishItalian "%1 present.txt"
CALL englishItalian "%1 imperfect.txt"
CALL englishItalian "%1 past.txt"
CALL englishItalian "%1 future.txt"
CALL englishItalian "%1 conditional.txt"
CALL englishItalian "%1 present subjunctive.txt"
